# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
env:
  - CONFIG=Debug
  - CONFIG=Release
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - cd tests
  - ./morton_test
